### ISSUE TITLE
Last update seems to have broken things for me.

### ISSUE THREAD

**Issue by aintnorest** [mvader/node-cordova#2]
plugin was working great when I tried to split off a new repo and use it to create an app it errored out. logging the return value gives:

{ _connecting: false,
  _handle:
   { fd: 14,
     writeQueueSize: 0,
     owner: [Circular],
     onread: [Function: onread],
     reading: true },
  _readableState:
   { highWaterMark: 16384,
     buffer: [],
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: false,
     ended: false,
     endEmitted: false,
     reading: true,
     calledRead: true,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     objectMode: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder:
      { encoding: 'utf8',
        surrogateSize: 3,
        charBuffer: <Buffer 00 00 00 00 01 00>,
        charReceived: 0,
        charLength: 0 },
     encoding: 'utf8' },
  readable: true,
  domain: null,
  _events:
   { end: { [Function: g] listener: [Function: onend] },
     finish: [Function: onSocketFinish],
     _socketEnd: [Function: onSocketEnd],
     close: [Function],
     data: [Function],
     readable: [Function] },
  _maxListeners: 10,
  _writableState:
   { highWaterMark: 16384,
     objectMode: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function],
     writecb: null,
     writelen: 0,
     buffer: [],
     errorEmitted: false },
  writable: false,
  allowHalfOpen: false,
  onend: null,
  destroyed: false,
  bytesRead: 0,
  _bytesDispatched: 0,
  _pendingData: null,
  _pendingEncoding: '',
  pipe: [Function],
  addListener: [Function: addListener],
  on: [Function: addListener],
  pause: [Function],
  resume: [Function],
  read: [Function],
  _consuming: true }

I grabbed the old version and replaced it for the new one and no problem at all. Let me know if I'm just being dumb and missed something.

**Comment by erizocosmico** [comment]
Yeah, the update must have broken something. On the inside now the library does not use shelljs but child_process and thus the output returned is different.

Can you post an example of code where the new version breaks with the previous one? I'll take a look at it and try to give you a solution.
